language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email: false

install:
    - pip install -q coverage coveralls
    - python setup.py develop

script:
  - coverage run --source geortree setup.py test

after_success:
    coveralls
